'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { AnimatedSection } from '@/components/animated-section';
import {
  ArrowLeft,
  Download,
  FileText,
  Briefcase,
  GraduationCap,
  Home,
  Laptop,
  Search,
  Plane,
  Building,
  Heart,
  Flag,
  BookOpen,
} from 'lucide-react';
import type { VisaInfo } from '@/lib/visa/types';
import { ChecklistProgress } from './ChecklistProgress';
import { ChecklistItem } from './ChecklistItem';
import { LegalDisclaimer } from '@/components/visa/LegalDisclaimer';

interface ChecklistPageProps {
  visa: VisaInfo;
}

const categoryIcons = {
  work: Briefcase,
  study: GraduationCap,
  residence: Home,
  'digital-nomad': Laptop,
  'job-seeking': Search,
  'working-holiday': Plane,
  business: Building,
  family: Heart,
  'ethnic-korean': Flag,
  'language-study': BookOpen,
};

const STORAGE_KEY_PREFIX = 'visa-checklist-';

export function ChecklistPage({ visa }: ChecklistPageProps) {
  const [checkedItems, setCheckedItems] = useState<Record<string, boolean>>({});
  const [mounted, setMounted] = useState(false);

  const Icon = categoryIcons[visa.category] || FileText;

  // Load from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem(`${STORAGE_KEY_PREFIX}${visa.type}`);
    if (stored) {
      try {
        setCheckedItems(JSON.parse(stored));
      } catch {
        // Invalid JSON, ignore
      }
    }
    setMounted(true);
  }, [visa.type]);

  // Save to localStorage on change
  useEffect(() => {
    if (mounted) {
      localStorage.setItem(
        `${STORAGE_KEY_PREFIX}${visa.type}`,
        JSON.stringify(checkedItems)
      );
    }
  }, [checkedItems, visa.type, mounted]);

  const handleToggle = (docId: string) => {
    setCheckedItems((prev) => ({
      ...prev,
      [docId]: !prev[docId],
    }));
  };

  const handleExport = () => {
    const requiredDocs = visa.documents.filter((d) => d.required);
    const optionalDocs = visa.documents.filter((d) => !d.required);

    let content = `${visa.name} - Document Checklist\n`;
    content += `${'='.repeat(50)}\n\n`;

    content += `REQUIRED DOCUMENTS\n`;
    content += `${'-'.repeat(30)}\n`;
    requiredDocs.forEach((doc) => {
      const checked = checkedItems[doc.id] ? '[x]' : '[ ]';
      content += `${checked} ${doc.name}\n`;
      if (doc.description) content += `    ${doc.description}\n`;
      content += '\n';
    });

    if (optionalDocs.length > 0) {
      content += `\nOPTIONAL DOCUMENTS\n`;
      content += `${'-'.repeat(30)}\n`;
      optionalDocs.forEach((doc) => {
        const checked = checkedItems[doc.id] ? '[x]' : '[ ]';
        content += `${checked} ${doc.name}\n`;
        if (doc.description) content += `    ${doc.description}\n`;
        content += '\n';
      });
    }

    content += `\n${'='.repeat(50)}\n`;
    content += `Generated by LocalNomad - ${new Date().toLocaleDateString()}\n`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${visa.type}-checklist.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Calculate progress
  const requiredDocs = visa.documents.filter((d) => d.required);
  const optionalDocs = visa.documents.filter((d) => !d.required);
  const totalCompleted = visa.documents.filter((d) => checkedItems[d.id]).length;
  const requiredCompleted = requiredDocs.filter((d) => checkedItems[d.id]).length;

  return (
    <div className="min-h-screen bg-[#0B1120]">
      {/* Hero Section */}
      <section className="pt-28 pb-8 px-4 sm:px-6 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-cyan-500/5 rounded-full blur-3xl" />

        <div className="container mx-auto max-w-4xl relative z-10">
          <AnimatedSection>
            {/* Breadcrumb */}
            <Link
              href={`/visa/${visa.type}`}
              className="inline-flex items-center text-sm text-slate-400 hover:text-white mb-6 transition-colors"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to {visa.shortName}
            </Link>

            <div className="flex items-start gap-4 mb-8">
              <div className="w-14 h-14 rounded-xl bg-cyan-500/10 flex items-center justify-center flex-shrink-0">
                <Icon className="w-7 h-7 text-cyan-400" />
              </div>
              <div>
                <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">
                  {visa.shortName} Document Checklist
                </h1>
                <p className="text-slate-400">
                  Track your document preparation for {visa.name}
                </p>
              </div>
            </div>

            {/* Progress */}
            <ChecklistProgress
              completed={totalCompleted}
              total={visa.documents.length}
              requiredCompleted={requiredCompleted}
              requiredTotal={requiredDocs.length}
            />
          </AnimatedSection>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-8 px-4 sm:px-6">
        <div className="container mx-auto max-w-4xl">
          {/* Actions */}
          <div className="flex justify-end mb-6">
            <Button
              variant="outline"
              size="sm"
              onClick={handleExport}
              className="border-slate-700 text-slate-300 hover:bg-slate-800"
            >
              <Download className="w-4 h-4 mr-2" />
              Export Checklist
            </Button>
          </div>

          {/* Required Documents */}
          <AnimatedSection>
            <div className="mb-8">
              <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-xs">
                  {requiredDocs.length}
                </span>
                Required Documents
              </h2>
              <div className="space-y-3">
                {requiredDocs.map((doc) => (
                  <ChecklistItem
                    key={doc.id}
                    document={doc}
                    checked={!!checkedItems[doc.id]}
                    onToggle={() => handleToggle(doc.id)}
                  />
                ))}
              </div>
            </div>
          </AnimatedSection>

          {/* Optional Documents */}
          {optionalDocs.length > 0 && (
            <AnimatedSection>
              <div className="mb-8">
                <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                  <span className="w-6 h-6 rounded-full bg-slate-700 text-slate-400 flex items-center justify-center text-xs">
                    {optionalDocs.length}
                  </span>
                  Optional Documents
                </h2>
                <div className="space-y-3">
                  {optionalDocs.map((doc) => (
                    <ChecklistItem
                      key={doc.id}
                      document={doc}
                      checked={!!checkedItems[doc.id]}
                      onToggle={() => handleToggle(doc.id)}
                    />
                  ))}
                </div>
              </div>
            </AnimatedSection>
          )}

          {/* Disclaimer */}
          <AnimatedSection>
            <LegalDisclaimer variant="box" className="mt-8" />
          </AnimatedSection>
        </div>
      </section>
    </div>
  );
}
